### ISSUE TITLE
Format Includes not works in VS 2022

### ISSUE THREAD

**Issue by rlopezll** [Agrael1/IncludeToolbox#9]
I recieve this message when I try to do "Format Includes":

System.NullReferenceException: Object reference not set to an instance of an object.
   at IncludeToolbox.VCUtil.<GetIncludeDirsAsync>d__8.MoveNext() in D:\a\IncludeToolbox\IncludeToolbox\IncludeToolboxShared\Util\VCUtil.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IncludeToolbox.Commands.FormatIncludes.<ExecuteAsync>d__3.MoveNext() in D:\a\IncludeToolbox\IncludeToolbox\IncludeToolboxShared\Commands\FormatIncludes.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Community.VisualStudio.Toolkit.BaseCommand.<>c__DisplayClass8_0.<<Execute>b__0>d.MoveNext()

**Comment by Agrael1** [comment]
what is in a file, that produces error and what are the settings?

**Comment by fakeranderson** [comment]
Hello, I too have encountered this issue. The error occurs in **all files**, but for the sake of diagnosis I am using an Unreal Engine 5 project and an example of a failure is the file is `Engine\Source\Developer\TraceAnalysis\Private\Analysis\Engine.cpp`. The failure is for these includes:
![image](https://user-images.githubusercontent.com/27230834/203399774-80b3364e-b55c-4a07-a14d-5a2b43e773af.png)

Here is the error output after `right click` -> `Format Includes`:
![image](https://user-images.githubusercontent.com/27230834/203399885-720e17b7-6f64-468c-9e05-8c4b5474a312.png)

Using VS22 Community 17.4.1. Also occurred using VS 22 Professional. Thank you for your time :)

**Comment by Agrael1** [comment]
thank you, will investigate the issue

**Comment by Agrael1** [comment]
I don't have full knowledge on where does UE put its include directories, but I queried them from VC++, hope that's enough

**Comment by fakeranderson** [comment]
It’s fixed for me, thank you!
